In [1]:
import pandas as pd
import numpy as np

In [2]:
trainingData = pd.read_csv("train.csv")
testingData = pd.read_csv("test.csv")

In [3]:
trainingData.head()

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0   0       3189      40      8                                30   
1   1       3026     182      5                               280   
2   2       3106      13      7                               351   
3   3       3022     276     13                               192   
4   4       2906     186     13                               266   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                              13                             3270   
1                              29                             3270   
2                              37                             2914   
3                              16                             3034   
4                              22                             2916   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm  ...  Soil_Type32  \
0            206             234            193  ...            0   
1            233             240            106  ...            0   
2            208             234            137  ...            0   
3            207             238            156  ...            0   
4            231             231            154  ...            0   

   Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type38  Soil_Type39  Soil_Type40  Cover_Type  
0            0            0            0           1  
1            0            0            0           2  
2            0            0            0           1  
3            0            0            0           2  
4            0            0            0           2  

[5 rows x 56 columns]

In [4]:
trainingData.columns

Index(['Id', 'Elevation', 'Aspect', 'Slope',
       'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology',
       'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon',
       'Hillshade_3pm', 'Horizontal_Distance_To_Fire_Points',
       'Wilderness_Area1', 'Wilderness_Area2', 'Wilderness_Area3',
       'Wilderness_Area4', 'Soil_Type1', 'Soil_Type2', 'Soil_Type3',
       'Soil_Type4', 'Soil_Type5', 'Soil_Type6', 'Soil_Type7', 'Soil_Type8',
       'Soil_Type9', 'Soil_Type10', 'Soil_Type11', 'Soil_Type12',
       'Soil_Type13', 'Soil_Type14', 'Soil_Type15', 'Soil_Type16',
       'Soil_Type17', 'Soil_Type18', 'Soil_Type19', 'Soil_Type20',
       'Soil_Type21', 'Soil_Type22', 'Soil_Type23', 'Soil_Type24',
       'Soil_Type25', 'Soil_Type26', 'Soil_Type27', 'Soil_Type28',
       'Soil_Type29', 'Soil_Type30', 'Soil_Type31', 'Soil_Type32',
       'Soil_Type33', 'Soil_Type34', 'Soil_Type35', 'Soil_Type36',
       'Soil_Type37', 'Soil_Type38', 'Soil_Type39', 'Soil_

In [5]:
features = ['Elevation',
 'Aspect',
 'Slope',
 'Horizontal_Distance_To_Hydrology',
 'Vertical_Distance_To_Hydrology',
 'Horizontal_Distance_To_Roadways',
 'Hillshade_9am',
 'Hillshade_Noon',
 'Hillshade_3pm',
 'Horizontal_Distance_To_Fire_Points',
 ]

In [27]:
trainingData['Cover_Type'].unique()

array([1, 2, 3, 6, 7, 4, 5], dtype=int64)

In [7]:
X = trainingData.drop('Id', axis= 1)

In [8]:
X.drop('Cover_Type', axis=1, inplace= True)

In [9]:
X

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0             3189      40      8                                30   
1             3026     182      5                               280   
2             3106      13      7                               351   
3             3022     276     13                               192   
4             2906     186     13                               266   
...            ...     ...    ...                               ...   
3999995       2954      34     25                                51   
3999996       2926     104      8                               696   
3999997       2911     144      1                               509   
3999998       2580     178     17                               376   
3999999       3083     136      4                                44   

         Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                                    13                             3270   
1                                    29                             3270   
2                                    37                             2914   
3                                    16                             3034   
4                                    22                             2916   
...                                 ...                              ...   
3999995                              65                             6314   
3999996                              83                             5427   
3999997                              58                             4820   
3999998                              86                             2592   
3999999                               9                             1675   

         Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
0                  206             234            193   
1                  233             240            106   
2                  208             234            137   
3                  207             238            156   
4                  231             231            154   
...                ...             ...            ...   
3999995            240             237            103   
3999996            210             216            150   
3999997            195             192             91   
3999998            225             183             39   
3999999            213             197            205   

         Horizontal_Distance_To_Fire_Points  ...  Soil_Type31  Soil_Type32  \
0                                      4873  ...            0            0   
1                                      5423  ...            0            0   
2                                      5269  ...            0            0   
3                                      2866  ...            0            0   
4                                      2642  ...            0            0   
...                                     ...  ...          ...          ...   
3999995                                1618  ...            0            0   
3999996                                2863  ...            0            0   
3999997                                  92  ...            0            0   
3999998                                1374  ...            0            0   
3999999                                1612  ...            0            0   

         Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
0                  0            0            0            0            0   
1                  0            0            0            0            0   
2                  0            0            0            0            0   
3                  0            0            0            0            0   
4                  0            0            0            0            0   
...              ...          ...          ...          ...          ...   
3999995            0            0            0            0            0   
3999996      

In [10]:
y = trainingData['Cover_Type']

In [11]:
y

0          1
1          2
2          1
3          2
4          2
          ..
3999995    2
3999996    2
3999997    2
3999998    3
3999999    1
Name: Cover_Type, Length: 4000000, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 42)

In [14]:
#####FEATURE SCALING X_TRAIN AND X TEST 

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

ct = ColumnTransformer([
    ('transformer', StandardScaler(), features)], remainder='passthrough')

In [18]:
X_train_scaled = ct.fit_transform(X_train)

In [21]:
X_test_scaled = ct.transform(X_test)

In [22]:
X_test_scaled

array([[ 0.34491692, -0.1327897 ,  0.33967171, ...,  0.        ,
         0.        ,  0.        ],
       [-0.76934288, -1.20583626, -0.83054866, ...,  0.        ,
         0.        ,  0.        ],
       [-0.69667376, -0.59656406, -0.71352662, ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [-0.40599729,  0.28551658,  1.86095819, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.64597469,  0.13092513,  0.10562764, ...,  0.        ,
         1.        ,  0.        ],
       [-0.16030647,  0.24004851, -0.24543847, ...,  0.        ,
         0.        ,  0.        ]])

So far have: 
X_test Scaled 
X_train Scaled 
y_train and y_test are catagorical values unscaled! 

NOW ON TO TRAINING! 
AND CHECKING! 

WHICH ALGO TO USE? 


In [28]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, random_state= 42, criterion='entropy')
classifier.fit(X_train_scaled, y_train)


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=42)

In [29]:
y_pred = classifier.predict(X_test_scaled)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[283469   8690      0      0      0    977]
 [ 11737 438389   2443      0     76     34]
 [     0   5920  33322      6    147      0]
 [     0      0     72      9      0      0]
 [     0    442   1211      0    618      0]
 [  5385     75      0      0      0   6978]]


0.95348125

SHEEEESH 95% ON FIRST TRY?


In [32]:
testingData.head()

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0  4000000       2763      78     20                               377   
1  4000001       2826     153     11                               264   
2  4000002       2948      57     19                                56   
3  4000003       2926     119      6                               158   
4  4000004       2690      10      4                                38   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                              88                             3104   
1                              39                              295   
2                              44                              852   
3                             134                             2136   
4                             108                             3589   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm  ...  Soil_Type31  \
0            218             213            195  ...            0   
1            219             238            148  ...            0   
2            202             217            163  ...            0   
3            234             240            142  ...            0   
4            213             221            229  ...            0   

   Soil_Type32  Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            1            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   Soil_Type37  Soil_Type38  Soil_Type39  Soil_Type40  
0            0            0            0            0  
1            0            0            0            0  
2            0            0            0            0  
3            0            0            0            0  
4            0            0            0            0  

[5 rows x 55 columns]

In [33]:
ID = testingData["Id"]

In [34]:
ID

0         4000000
1         4000001
2         4000002
3         4000003
4         4000004
           ...   
999995    4999995
999996    4999996
999997    4999997
999998    4999998
999999    4999999
Name: Id, Length: 1000000, dtype: int64

In [37]:
testingData.drop('Id',axis=1, inplace=True)

In [38]:
testingData

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0            2763      78     20                               377   
1            2826     153     11                               264   
2            2948      57     19                                56   
3            2926     119      6                               158   
4            2690      10      4                                38   
...           ...     ...    ...                               ...   
999995       2974     254     15                               146   
999996       3180      92     16                                93   
999997       2684      51     20                                34   
999998       3309      64     12                               196   
999999       2543     322      7                               162   

        Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                                   88                             3104   
1                                   39                              295   
2                                   44                              852   
3                                  134                             2136   
4                                  108                             3589   
...                                ...                              ...   
999995                             100                              623   
999996                              47                             3740   
999997                             123                              962   
999998                              93                             2522   
999999                             147                             2643   

        Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
0                 218             213            195   
1                 219             238            148   
2                 202             217            163   
3                 234             240            142   
4                 213             221            229   
...               ...             ...            ...   
999995            222             245            117   
999996            209             201            142   
999997            199             225            145   
999998            226             193             74   
999999            223             222             82   

        Horizontal_Distance_To_Fire_Points  ...  Soil_Type31  Soil_Type32  \
0                                     1931  ...            0            0   
1                                     2557  ...            0            0   
2                                     1803  ...            0            0   
3                                      857  ...            0            0   
4                                      431  ...            0            0   
...                                    ...  ...          ...          ...   
999995                                2353  ...            0            0   
999996                                 356  ...            0            0   
999997                                 350  ...            0            0   
999998                                3300  ...            0            0   
999999                                 657  ...            0            0   

        Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
0                 0            0            0            0            0   
1                 0            0            0            0            0   
2                 1            0            0            0            0   
3                 0            0            0            0            0   
4                 0            0            0            0            0   
...             ...          ...          ...          ...          ...   
999995            0            0            0            0            0   
999996            0            0            0            0          

In [40]:
scaledTestingData = ct.transform(testingData)

In [41]:
scaledTestingData

array([[-0.75204071, -0.66931298,  0.57371579, ...,  0.        ,
         0.        ,  0.        ],
       [-0.53403336,  0.01270814, -0.47948255, ...,  0.        ,
         0.        ,  0.        ],
       [-0.11186039, -0.8602789 ,  0.45669375, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.02541501, -0.91484058,  0.57371579, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.13735635, -0.79662359, -0.36246051, ...,  0.        ,
         0.        ,  0.        ],
       [-1.51333622,  1.54952906, -0.94757069, ...,  0.        ,
         0.        ,  0.        ]])

In [42]:
answer = classifier.predict(scaledTestingData)

In [43]:
answer

array([2, 2, 2, ..., 2, 1, 3], dtype=int64)

In [47]:
output = pd.DataFrame({'Id': ID, 'Cover_Type': answer})

In [48]:
output

Id  Cover_Type
0       4000000           2
1       4000001           2
2       4000002           2
3       4000003           2
4       4000004           2
...         ...         ...
999995  4999995           2
999996  4999996           1
999997  4999997           2
999998  4999998           1
999999  4999999           3

[1000000 rows x 2 columns]

In [49]:
output.to_csv('submission.csv', index=False)